# Generated by Django 2.0.1 on 2018-08-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180509_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numReads',
            field=models.IntegerField(default=0, verbose_name='Numero Leituras'),
        ),
    ]
